### ISSUE TITLE
UnboundLocalError while preparing Mapillary dataset 

### ISSUE THREAD

**Issue by MohammedAIHamed** [facebookresearch/OrienterNet#18]
When running python3 -m maploc.data.mapillary.prepare --token $MAPILLARY_TOKEN I get the following error:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mohammed/Desktop/Maynooth/Dev/OrienterNet-main/maploc/data/mapillary/prepare.py", line 399, in <module>
    process_location(
  File "/home/mohammed/Desktop/Maynooth/Dev/OrienterNet-main/maploc/data/mapillary/prepare.py", line 372, in process_location
    plotter.bbox(projection.unproject(bbox_tiling), "black", "tiling bounding box")
UnboundLocalError: local variable 'bbox_tiling' referenced before assignment

I'm using Python 3.10.12 on Ubuntu 22.04 LTS

**Comment by Skydes** [comment]
Fixed by https://github.com/facebookresearch/OrienterNet/commit/442a6ccaf8784274367af291d218b2d283d8b6d7.
