### ISSUE TITLE
Question about MGL Dataset

### ISSUE THREAD

**Issue by TechnoNeko** [facebookresearch/OrienterNet#43]
There is no issue when using the prepare.py with the KITTI dataset, but there is a problem of connection interruption when using prepare.py with the MGL dataset. How can I fix it?

/home/dyh/anaconda3/envs/dataset/bin/python /home/dyh/Project/OrienterNet/maploc/data/mapillary/prepare.py 
[2024-01-22 21:14:55 maploc INFO] Starting processing for location sanfrancisco_soma.
[2024-01-22 21:14:55 maploc INFO] Fetching metadata for all images.
  5%|▍         | 1884/41861 [00:24<08:32, 78.02it/s]
Traceback (most recent call last):
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 78, in start_tls
    raise exc
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 69, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/anyio/streams/tls.py", line 132, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/anyio/streams/tls.py", line 147, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1132, in receive
    raise self._protocol.exception from None
anyio.BrokenResourceError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_transports/default.py", line 67, in map_httpcore_exceptions
    yield
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
    raise exc
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_async/http_proxy.py", line 317, in handle_async_request
    stream = await stream.start_tls(**kwargs)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_backends/anyio.py", line 78, in start_tls
    raise exc
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/prepare.py", line 410, in <module>
    process_location(
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/prepare.py", line 305, in process_location
    image_infos, num_fail = loop.run_until_complete(
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/download.py", line 139, in fetch_image_infos
    i, info = await task
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/download.py", line 130, in fetch_image_info
    info = await downloader.get_image_info_cached(i, path)
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/download.py", line 95, in get_image_info_cached
    info = await self.get_image_info(image_id)
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/download.py", line 74, in get_image_info
    r = await self.call_api(url)
  File "/home/dyh/Project/OrienterNet/maploc/data/mapillary/download.py", line 63, in call_api
    r = await self.client.get(url)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_client.py", line 1786, in get
    return await self.request(
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_client.py", line 1646, in send
    response = await self._send_handling_auth(
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_client.py", line 1674, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_client.py", line 1711, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_client.py", line 1748, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_transports/default.py", line 371, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dyh/anaconda3/envs/dataset/lib/python3.8/site-packages/httpx/_transports/default.py", line 84, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

**Comment by sarlinpe** [comment]
Can you try again now that https://github.com/facebookresearch/OrienterNet/commit/41d2f9d5f14a637a84c99ae2e7fb8ba500fde2d1 has been merged?

If not, how about replacing 
https://github.com/facebookresearch/OrienterNet/blob/41d2f9d5f14a637a84c99ae2e7fb8ba500fde2d1/maploc/data/mapillary/download.py#L69
with 

```diff
-    @retry(times=5, exceptions=(httpx.RemoteProtocolError, httpx.ReadError))
+    @retry(times=5, exceptions=(httpx.RemoteProtocolError, httpx.ReadError, httpx.ConnectError))
```
